config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :meetings, only: [:create, :update]
  devise_for :users

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :meetings

  acts_as_taggable

  def available?
  	meetings.where(end_datetime: nil).empty?
  end
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_many :books
 	has_many :meetings

 	def meeting_books
 		meetings.where(end_datetime: nil)
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @meeting = current_user.meetings.build(book_id: @book.id)
  end

  # GET /books/new
  def new
    # @book = Book.new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :user_id, :tag_list)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:update]

  def create
  	@meeting = Meeting.new(meeting_params)
  	@meeting.start_datetime = Time.now

  	@meeting.save
  	redirect_to @meeting.book
  end

  def update
    @meeting.update(meeting_params)
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:user_id, :book_id, :end_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :tag_list %>
    <%= f.hidden_field :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<% if user_signed_in? && current_user.meeting_books.any? %>
  <% current_user.meeting_books.each do |meeting| %>
    <div class="alert alert-info" role="alert">
      <%= meeting.book.id %>번 책과 데이트 중
      <%= simple_form_for meeting do |f| %>
        <%= f.hidden_field :end_datetime, value: Time.now %>
        <%= f.submit "데이트 끝내기", class: "btn btn-default" %>
      <% end %>
    </div>
  <% end %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.user.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @book.id %> - <%= @book.tag_list %></h3>

<p>주선자: <%= @book.user.name %></p>

<% if @book.available? %>
	<%= simple_form_for @meeting do |f| %>
		<%= f.hidden_field :user_id %>
		<%= f.hidden_field :book_id %>
		<%= f.submit "데이트 시작하기", class: "btn btn-success" %>
	<% end %>
<% end %>

<% @book.meetings.each do |meeting| %>
	<div>
		<%= meeting.user.name %> - <%= meeting.start_datetime %> - <%= meeting.start_datetime + 21.days %>
	</div>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blindbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Blind Book", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
    	<li>
    		<% if user_signed_in? %>
    			<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    		<% else %>
    			<%= link_to "Log In", new_user_session_path %>
    		<% end %>
    	</li>
    </ul>
  </div>
</nav>
<div class="container">
	<%= yield %>
</div>

</body>
</html>